id: A2C191F29
title: In Praise of the Protector Mañjughoṣa
type: translation
pechas:
- IF9A02F88
- IF7F4EE8A
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:10:57.963199
  last_modified_at: 2023-01-04 13:10:57.963206
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  IF9A02F88/2802: D9ED
  IF7F4EE8A/2C2A: D9ED
